name: Checkov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  checkov-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@5b9a80d87687cf43fda4b7e9893e21d31d6eed4a # v12.2968.0
        with:
          directory: /
          framework: terraform 
          output_format: sarif
          config_file: checkov.yml
          skip_check: CKV_TF_1,CKV_AWS_28,CKV_AWS_119,CKV_AWS_33,CKV2_AWS_16,CKV_AWS_144,CKV_AWS_18,CKV2_AWS_38,CKV2_AWS_57,CKV2_AWS_62,CKV2_AWS_39,CKV2_AWS_61,CKV_AWS_149,CKV_AWS_7,CKV2_AWS_64
