name: Checkov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: /
          framework: terraform 
          output_format: sarif
          config_file: checkov.yml
          skip_check: CKV_TF_1,CKV_AWS_28,CKV_AWS_119,CKV_AWS_33, # Skip a specific check_id. Can be comma separated list.
