name: Generate terraform docs
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  terraform-docs:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the documentation.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1
      with:
        working-dir: .
        output-file: readme.md
        output-method: inject
        git-push: "true"
        template: "<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->\n{{ .Content }}\n<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->"
