name: tf-lint
on:
  push:
    branches: main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tflint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@@8093687ecc9dcbfa88d07c103ad4176739a7287e # v4.1.0
      name: Setup TFLint
      with:
        tflint_version: v0.55.1

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
