name: tf-lint
on:
  push:
    branches: main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tflint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@11bd719 # 4.2.2
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@8093687 # 4.1.0
      name: Setup TFLint
      with:
        tflint_version: v0.53.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
